server:
  port: 8081

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/PlaxiDB
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: asapsitterapp@gmail.com
    password: ureeixyewmaiumra
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket-name: fotoperfil

